# -*- coding: utf-8 -*-
"""portfolio_charts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGDwqun0HD_fXykQ8uXICrENkkL-EyKj

## Portfolio Charts

### Import Libraries
"""

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
import matplotlib.ticker as mticker
from matplotlib.gridspec import GridSpec
from matplotlib.colors import LinearSegmentedColormap

"""### Style"""

REGIME_COLORS = {
    0: "#2ECC71",   # green — Low-Vol Bull
    1: "#F39C12",   # amber — Medium-Vol Normal
    2: "#E74C3C",   # red   — High-Vol Crisis
}
REGIME_ALPHA  = 0.18
REGIME_LABELS = {
    0: "Low-Vol (Bull)",
    1: "Medium-Vol (Normal)",
    2: "High-Vol (Crisis)",
}

ETF_COLORS = {
    "XIU.TO":   "#1f77b4",   # blue
    "VFV.TO":   "#2ca02c",   # green
    "XEF.TO":   "#9467bd",   # purple
    "XBB.TO":   "#ff7f0e",   # orange
    "CGL-C.TO": "#bcbd22",   # olive/gold
}
ETF_NAMES = {
    "XIU.TO":   "XIU — TSX 60",
    "VFV.TO":   "VFV — S&P 500 (CAD)",
    "XEF.TO":   "XEF — EAFE Intl",
    "XBB.TO":   "XBB — Cdn Bonds",
    "CGL-C.TO": "CGL — Gold",
}

STRESS_EVENTS = {
    "Oil Crash":   ("2015-08-01", "2016-02-28"),
    "COVID Crash": ("2020-02-20", "2020-05-31"),
    "Rate Shock":  ("2022-01-01", "2022-12-31"),
}

"""### Helper Fn."""

INPUT_FILE = "/content/data_with_regimes.csv"
OUTPUT_DIR = "/content"

def shade_regimes(ax, dates, regimes):
    for r, color in REGIME_COLORS.items():
        mask = regimes == r
        ax.fill_between(dates, 0, 1,
                        where=mask,
                        transform=ax.get_xaxis_transform(),
                        color=color, alpha=REGIME_ALPHA,
                        linewidth=0, zorder=0)

def add_stress_labels(ax):
    ylim = ax.get_ylim()
    for label, (start, _) in STRESS_EVENTS.items():
        ax.axvline(pd.Timestamp(start), color="grey",
                   linewidth=0.8, linestyle="--", alpha=0.6)
        ax.text(pd.Timestamp(start), ylim[1],
                f" {label}", fontsize=7, color="grey",
                va="top", ha="left")

def year_ticks(ax):
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=0)

def regime_patches():
    return [mpatches.Patch(color=REGIME_COLORS[r], alpha=0.7,
                           label=REGIME_LABELS[r])
            for r in sorted(REGIME_LABELS)]

def clean_ax(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="y", linestyle="--", alpha=0.4)

"""### Load Data"""

print("Loading data_with_regimes.csv ...")
df = pd.read_csv(INPUT_FILE, index_col="Date", parse_dates=True)
df.sort_index(inplace=True)

etf_tickers = [c.replace("_Return", "") for c in df.columns
               if c.endswith("_Return")
               and c.replace("_Return", "") in ETF_COLORS]
ret_cols = [f"{t}_Return" for t in etf_tickers]

regimes = df["Regime"].fillna(method="ffill")
dates   = df.index
n       = len(etf_tickers)

print(f"  {len(df)} rows | {n} ETFs | {regimes.notna().sum()} days with labels")

"""### Charts"""

# ── 4. Chart 1: Cumulative Returns ─────────────────────────────────────────

print("\nChart 1/5 — Cumulative returns ...")

fig, axes = plt.subplots(n, 1, figsize=(14, 3 * n), sharex=True)
fig.suptitle("Portfolio Cumulative Returns by Market Regime",
             fontsize=14, fontweight="bold", y=1.01)

for ax, ticker in zip(axes, etf_tickers):
    col    = f"{ticker}_Return"
    color  = ETF_COLORS[ticker]
    cumret = (1 + df[col].fillna(0)).cumprod()

    shade_regimes(ax, dates, regimes)
    ax.plot(dates, cumret, color=color, linewidth=1.5,
            label=ETF_NAMES[ticker])
    ax.axhline(1.0, color="black", linewidth=0.5,
               linestyle="--", alpha=0.3)

    final = cumret.dropna().iloc[-1]
    ax.annotate(f"{final:.2f}×",
                xy=(dates[-1], final),
                xytext=(5, 0), textcoords="offset points",
                fontsize=8, va="center", color=color)

    ax.set_ylabel("Cumul. Return", fontsize=9)
    ax.yaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _: f"{x:.1f}×"))
    ax.legend(loc="upper left", fontsize=9, framealpha=0)
    clean_ax(ax)

year_ticks(axes[-1])
add_stress_labels(axes[-1])

fig.legend(handles=regime_patches(), loc="lower center", ncol=3,
           bbox_to_anchor=(0.5, -0.03), fontsize=9, framealpha=0.9)
plt.tight_layout()
out1 = os.path.join(OUTPUT_DIR, "chart_portfolio_regime_performance.png")
fig.savefig(out1, dpi=150, bbox_inches="tight")
plt.close()
print(f"  OK — {out1}")

# ── 5. Chart 2: Return Distribution Violins ────────────────────────────────

print("\nChart 2/5 — Return distributions ...")

fig, axes = plt.subplots(1, n, figsize=(3.2 * n, 6), sharey=False)
fig.suptitle("Daily Return Distributions by Regime",
             fontsize=14, fontweight="bold")

for ax, ticker in zip(axes, etf_tickers):
    col   = f"{ticker}_Return"
    color = ETF_COLORS[ticker]

    data_by_regime = []
    for r in range(3):
        vals = df.loc[regimes == r, col].dropna().values * 100
        data_by_regime.append(vals if len(vals) > 5 else np.array([0.0]))

    parts = ax.violinplot(data_by_regime, positions=[0, 1, 2],
                          showmedians=True, showextrema=False, widths=0.6)

    for pc, r in zip(parts["bodies"], range(3)):
        pc.set_facecolor(REGIME_COLORS[r])
        pc.set_edgecolor(REGIME_COLORS[r])
        pc.set_alpha(0.55)
    parts["cmedians"].set_color("black")
    parts["cmedians"].set_linewidth(1.5)

    ax.axhline(0, color="black", linewidth=0.6, linestyle="--", alpha=0.4)

    for r, vals in enumerate(data_by_regime):
        if len(vals) > 1:
            ax.text(r, np.percentile(vals, 97),
                    f"μ={np.mean(vals):.2f}%",
                    ha="center", fontsize=7)

    ax.set_xticks([0, 1, 2])
    ax.set_xticklabels(["Bull", "Normal", "Crisis"], fontsize=9)
    ax.set_title(ETF_NAMES.get(ticker, ticker),
                 fontsize=9, color=color, fontweight="bold")
    if ax == axes[0]:
        ax.set_ylabel("Daily Return (%)", fontsize=9)
    ax.yaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _: f"{x:.1f}%"))
    clean_ax(ax)

plt.tight_layout()
out2 = os.path.join(OUTPUT_DIR, "chart_regime_return_distributions.png")
fig.savefig(out2, dpi=150, bbox_inches="tight")
plt.close()
print(f"  OK — {out2}")

# ── 6. Chart 3: Regime Heatmap ────────────────────────────────────────────

print("\nChart 3/5 — Regime heatmap ...")

row_labels = [ETF_NAMES.get(t, t) for t in etf_tickers]
ann_ret    = np.full((n, 3), np.nan)
ann_vol    = np.full((n, 3), np.nan)
sharpe     = np.full((n, 3), np.nan)

for r in range(3):
    mask = regimes == r
    for i, ticker in enumerate(etf_tickers):
        vals = df.loc[mask, f"{ticker}_Return"].dropna()
        if len(vals) > 5:
            ar = vals.mean() * 252
            av = vals.std()  * np.sqrt(252)
            ann_ret[i, r] = ar
            ann_vol[i, r] = av
            sharpe[i, r]  = ar / av if av > 0 else np.nan

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.suptitle("Regime Characteristics — Full Portfolio",
             fontsize=14, fontweight="bold", y=1.02)

datasets = [
    (ann_ret, "Annualised Return",   "RdYlGn", lambda v: f"{v:+.1%}"),
    (ann_vol, "Annualised Volatility","YlOrRd", lambda v: f"{v:.1%}"),
    (sharpe,  "Sharpe Ratio",        "RdYlGn", lambda v: f"{v:.2f}"),
]

for ax, (data, title, cmap, fmt) in zip(axes, datasets):
    vabs = np.nanmax(np.abs(data))
    vmin = -vabs if cmap == "RdYlGn" else 0
    im   = ax.imshow(data, cmap=cmap, vmin=vmin, vmax=vabs, aspect="auto")
    plt.colorbar(im, ax=ax, shrink=0.8, pad=0.02)

    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            v = data[i, j]
            if not np.isnan(v):
                ax.text(j, i, fmt(v),
                        ha="center", va="center",
                        fontsize=9, fontweight="bold", color="black")

    ax.set_xticks(range(3))
    ax.set_xticklabels(["Bull", "Normal", "Crisis"], fontsize=9)
    ax.set_yticks(range(n))
    ax.set_yticklabels(row_labels if ax == axes[0] else [], fontsize=8)
    ax.set_title(title, fontsize=11, fontweight="bold", pad=10)

plt.tight_layout()
out3 = os.path.join(OUTPUT_DIR, "chart_regime_heatmap.png")
fig.savefig(out3, dpi=150, bbox_inches="tight")
plt.close()
print(f"  OK — {out3}")

# ── 7. Chart 4: Drawdown Curves ────────────────────────────────────────────

print("\nChart 4/5 — Drawdown curves ...")

fig, axes = plt.subplots(n, 1, figsize=(14, 2.8 * n), sharex=True)
fig.suptitle("Portfolio Drawdowns by Market Regime",
             fontsize=14, fontweight="bold", y=1.01)

for ax, ticker in zip(axes, etf_tickers):
    col      = f"{ticker}_Return"
    color    = ETF_COLORS[ticker]
    cumret   = (1 + df[col].fillna(0)).cumprod()
    drawdown = (cumret - cumret.cummax()) / cumret.cummax()

    shade_regimes(ax, dates, regimes)
    ax.fill_between(dates, drawdown, 0, color=color, alpha=0.3)
    ax.plot(dates, drawdown, color=color, linewidth=1.2,
            label=ETF_NAMES[ticker])
    ax.axhline(0, color="black", linewidth=0.5, alpha=0.3)

    min_dd   = drawdown.min()
    min_date = drawdown.idxmin()
    ax.scatter(min_date, min_dd, color="red", s=35, zorder=5)
    ax.annotate(f"{min_dd:.1%}",
                xy=(min_date, min_dd),
                xytext=(10, -2), textcoords="offset points",
                fontsize=7.5, color="red")

    ax.set_ylabel("Drawdown", fontsize=9)
    ax.yaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _: f"{x:.0%}"))
    ax.set_ylim(min(drawdown.min() * 1.25, -0.02), 0.02)
    ax.legend(loc="lower left", fontsize=9, framealpha=0)
    clean_ax(ax)

year_ticks(axes[-1])
add_stress_labels(axes[-1])

fig.legend(handles=regime_patches(), loc="lower center", ncol=3,
           bbox_to_anchor=(0.5, -0.03), fontsize=9, framealpha=0.9)
plt.tight_layout()
out4 = os.path.join(OUTPUT_DIR, "chart_portfolio_drawdowns.png")
fig.savefig(out4, dpi=150, bbox_inches="tight")
plt.close()
print(f"  OK — {out4}")

# ── 8. Chart 5: Correlation Matrices Per Regime ────────────────────────────

print("\nChart 5/5 — Correlation shift ...")

short = {t: t.replace(".TO", "").replace("-C", "") for t in etf_tickers}

fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))
fig.suptitle("How Correlations Shift Across Regimes",
             fontsize=14, fontweight="bold")

for ax, r in zip(axes, range(3)):
    mask     = regimes == r
    ret_data = df.loc[mask, ret_cols].rename(
        columns={f"{t}_Return": short[t] for t in etf_tickers}
    ).dropna()
    corr   = ret_data.corr()
    labels = list(corr.columns)

    im = ax.imshow(corr.values, cmap="RdYlGn",
                   vmin=-1, vmax=1, aspect="auto")

    ax.set_xticks(range(len(labels)))
    ax.set_yticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=9)
    ax.set_yticklabels(labels if r == 0 else [], fontsize=9)

    for i in range(corr.shape[0]):
        for j in range(corr.shape[1]):
            v = corr.values[i, j]
            ax.text(j, i, f"{v:.2f}",
                    ha="center", va="center",
                    fontsize=8.5, fontweight="bold",
                    color="black" if abs(v) < 0.7 else "white")

    n_days = int(mask.sum())
    ax.set_title(f"{REGIME_LABELS[r]}\n({n_days} days)",
                 fontsize=10, fontweight="bold",
                 color=REGIME_COLORS[r], pad=8)

    for spine in ax.spines.values():
        spine.set_edgecolor(REGIME_COLORS[r])
        spine.set_linewidth(2)

cbar_ax = fig.add_axes([0.92, 0.15, 0.015, 0.65])
plt.colorbar(im, cax=cbar_ax, label="Correlation")

plt.tight_layout(rect=[0, 0, 0.91, 0.95])
out5 = os.path.join(OUTPUT_DIR, "chart_correlation_shift.png")
fig.savefig(out5, dpi=150, bbox_inches="tight")
plt.close()
print(f"  OK — {out5}")

